name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: fedora:latest
      env:
        PKG_CONFIG_ALLOW_CROSS: 1
    steps:
        - uses: actions/checkout@v1
        - run: |
              dnf install -y gtk4-devel libarchive-devel libwebp-devel jpegxl-devel curl make automake gcc gcc-c++ kernel-devel mingw64-gcc

              curl https://sh.rustup.rs -sSf | sh -s -- -y

              PATH=$PATH:$HOME/.cargo/bin

              cat <<'EOT' >> $HOME/.cargo/config.toml
              [target.x86_64-pc-windows-gnu]
              linker = "x86_64-w64-mingw32-gcc"
              ar = "x86_64-w64-mingw32-gcc-ar"
              EOT

              chmod +x ./zigc-wrapper.sh
              chmod +x ./zigcxx-wrapper.sh
              cp zigc-wrapper.sh $HOME/.cargo/bin
              cp zigcxx-wrapper.sh $HOME/.cargo/bin

              export RUSTFLAGS="-C link-arg=-Wl,--verbose"
              export RUSTC_LOG=rustc_codegen_ssa::back::link=info
              rustup target add x86_64-pc-windows-gnu

              cargo build --release --target=x86_64-pc-windows-gnu --verbose


          name: Build for Windows